# Generated by Django 2.1.7 on 2019-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/home/job/Desktop/com423/static/media/Avocado_A-Z_Fruit3.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
